/home/user/projects/virtual_mic/fifo_reader_writer/a.out /home/user/projects/virtual_mic/audios/2023_biology/biology_part1.wav
/home/user/projects/virtual_mic/fifo_reader_writer/a.out /home/user/projects/virtual_mic/audios/2023_biology/biology_part2.wav
/home/user/projects/virtual_mic/fifo_reader_writer/a.out /home/user/projects/virtual_mic/audios/2023_biology/biology_part3.wav
/home/user/projects/virtual_mic/fifo_reader_writer/a.out /home/user/projects/virtual_mic/audios/2023_math/math_part1.wav
/home/user/projects/virtual_mic/fifo_reader_writer/a.out /home/user/projects/virtual_mic/audios/2023_math/math_part2.wav
/home/user/projects/virtual_mic/fifo_reader_writer/a.out /home/user/projects/virtual_mic/audios/2023_math/math_part3.wav
/home/user/projects/virtual_mic/fifo_reader_writer/a.out /home/user/projects/virtual_mic/audios/2023_physics/physics_part1.wav
/home/user/projects/virtual_mic/fifo_reader_writer/a.out /home/user/projects/virtual_mic/audios/2023_physics/physics_part2.wav
/home/user/projects/virtual_mic/fifo_reader_writer/a.out /home/user/projects/virtual_mic/audios/2023_physics/physics_part2.wav